apiVersion: v1
kind: ConfigMap
metadata:
  name: dbfile-config
data:
  initdb.sql: |-
    -- MySQL dump 10.13  Distrib 5.7.32-35, for debian-linux-gnu (x86_64)
    --
    -- Host: localhost    Database: ideascale
    -- ------------------------------------------------------
    -- Server version	5.7.32-35-log

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
    /*!50717 SELECT COUNT(*) INTO @rocksdb_has_p_s_session_variables FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'performance_schema' AND TABLE_NAME = 'session_variables' */;
    /*!50717 SET @rocksdb_get_is_supported = IF (@rocksdb_has_p_s_session_variables, 'SELECT COUNT(*) INTO @rocksdb_is_supported FROM performance_schema.session_variables WHERE VARIABLE_NAME=\'rocksdb_bulk_load\'', 'SELECT 0') */;
    /*!50717 PREPARE s FROM @rocksdb_get_is_supported */;
    /*!50717 EXECUTE s */;
    /*!50717 DEALLOCATE PREPARE s */;
    /*!50717 SET @rocksdb_enable_bulk_load = IF (@rocksdb_is_supported, 'SET SESSION rocksdb_bulk_load = 1', 'SET @rocksdb_dummy_bulk_load = 0') */;
    /*!50717 PREPARE s FROM @rocksdb_enable_bulk_load */;
    /*!50717 EXECUTE s */;
    /*!50717 DEALLOCATE PREPARE s */;

    --
    -- Current Database: `ideascale`
    --

    CREATE DATABASE /*!32312 IF NOT EXISTS*/ `ideascale` /*!40100 DEFAULT CHARACTER SET latin1 */;

    USE `ideascale`;

    --
    -- Table structure for table `abuse_log`
    --

    DROP TABLE IF EXISTS `abuse_log`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!40101 SET character_set_client = utf8 */;
    CREATE TABLE `abuse_log` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `user_id` int(11) NOT NULL DEFAULT '0',
      `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      `ip_address` varchar(16) DEFAULT NULL,
      `email_address` varchar(128) DEFAULT NULL,
      `abuse_type` int(11) DEFAULT NULL,
      `key_id` int(11) DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `user_id` (`user_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    /*!40101 SET character_set_client = @saved_cs_client */;
