apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      #      initContainers:
      #        - name: initdb
      #          image: busybox:latest
      #          volumeMounts:
      #            - mountPath: /temp
      #              name: init-db
      #            - mountPath: /tempData
      #              name: my-config-map
      #          command:
      #            - cp
      #            - /tempData/initdb.sql
      #            - /temp
      #      containers:
      #        - name: mysql
      #          image: mysql:latest
      #          env:
      #            - name: MYSQL_ROOT_PASSWORD
      #              value: brewski01
      #          volumeMounts:
      #            - mountPath: /docker-entrypoint-initdb.d/
      #              name: init-db
      #      volumes:
      #        - name: init-db
      #        - name: my-config-map
      #          configMap:
      #            name: dbfile-config

      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: brewski01
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: my-config-map
      volumes:
        - name: my-config-map
          configMap:
            name: dbfile-config





