apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - image: my-tomcat:latest
          imagePullPolicy: Never
          name: tomcat
          ports:
            - containerPort: 8080